name = "Promised-World-Client_Full"
author = "Many-Stars"
version = "1.0.0.0-beta.1+26A4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a698b7b42d27790334abd6a85589795d000ff86e06d0ba0abcd80be0aa95be12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
