name = "Promised-World-Client_Full"
author = "Many-Stars"
version = "1.0.0.0-beta.1+26A3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "254cd129589911ea8a794f62c5e546cf76a5e2511bb1f95d96dfc15f69841023"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
